(async()=>{const ALLOWED_DOMAIN='event.vnggames.com';if(!location.hostname.includes(ALLOWED_DOMAIN)){alert('Tool chạy chỉ trên '+ALLOWED_DOMAIN);return;}const MANIFEST_URL='https://raw.githubusercontent.com/huihoangadm/td-tool-config/main/version.json';const PUB_PEM=`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGRpHBGnvFr5/B6Rx7+9
rgM03LLI9m7O3KNf0Q75u6892HLEAyIJwCY+sayUgpLp9gMFAlpy359+XoBW4L7Q
X7TJP93w7o+9giMNNU/2d8qNxRdZwum8esnWDPiv4amHenqX5H40m0a/SC2lmC4u
Grctv1aLEKCQtNbAA1Htf3Hh0VucN+hyOHZyuK17/wgCIxXoqCVGf99BD8jpycC6
h3pRYIjfwtSJq1Y/8w6iOME5RJOsDNfjOED4ACjll1+NgQIcf7ufvcc1edrSYcEe
4u+/cf8RU2HnMHfQBISOVGgFTQ4I9vKxqla6LxtwzzJzXery1NdwJ3KOTnYHBmyI
BQIDAQAB
-----END PUBLIC KEY-----
`;function pemToArrayBuffer(pem){const b64=pem.replace(/-----.*?-----/g,'').replace(/\s+/g,'');const bin=atob(b64);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return arr.buffer;}async function importPub(pem){const spki=pemToArrayBuffer(pem);return crypto.subtle.importKey('spki',spki,{name:'RSA-PSS',hash:'SHA-256'},false,['verify']);}try{const mf=await (await fetch(MANIFEST_URL+'?_='+Date.now())).json();const baseURL='https://raw.githubusercontent.com/huihoangadm/td-tool-config/main/';const [codeRes,sigRes]=await Promise.all([fetch(baseURL+mf.file+'?_='+Date.now()),fetch(baseURL+mf.sig+'?_='+Date.now())]);const codeText=await codeRes.text();const sigB64=await sigRes.text();const pub=await importPub(PUB_PEM);const enc=new TextEncoder();const ok=await crypto.subtle.verify({name:'RSA-PSS',saltLength:32},pub,Uint8Array.from(atob(sigB64.trim()),c=>c.charCodeAt(0)).buffer,enc.encode(codeText));if(!ok){alert('Chữ ký không hợp lệ — dừng chạy.');return;} (0,eval)(codeText);console.log('loader_v2.2.0: loaded',mf.version);}catch(e){console.error('loader error',e);alert('Không thể tải/kiểm tra file.');}})();